export const browserCoreExamples = [
  "sage browser status",
  "sage browser start",
  "sage browser stop",
  "sage browser tabs",
  "sage browser open https://example.com",
  "sage browser focus abcd1234",
  "sage browser close abcd1234",
  "sage browser screenshot",
  "sage browser screenshot --full-page",
  "sage browser screenshot --ref 12",
  "sage browser snapshot",
  "sage browser snapshot --format aria --limit 200",
  "sage browser snapshot --efficient",
  "sage browser snapshot --labels",
];

export const browserActionExamples = [
  "sage browser navigate https://example.com",
  "sage browser resize 1280 720",
  "sage browser click 12 --double",
  'sage browser type 23 "hello" --submit',
  "sage browser press Enter",
  "sage browser hover 44",
  "sage browser drag 10 11",
  "sage browser select 9 OptionA OptionB",
  "sage browser upload /tmp/file.pdf",
  'sage browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "sage browser dialog --accept",
  'sage browser wait --text "Done"',
  "sage browser evaluate --fn '(el) => el.textContent' --ref 7",
  "sage browser console --level error",
  "sage browser pdf",
];
