#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${SAGE_INSTALL_E2E_IMAGE:-${SAGEBOT_INSTALL_E2E_IMAGE:-sage-install-e2e:local}}"
INSTALL_URL="${SAGE_INSTALL_URL:-${SAGEBOT_INSTALL_URL:-https://sage.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
SAGE_E2E_MODELS="${SAGE_E2E_MODELS:-${SAGEBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e SAGE_INSTALL_URL="$INSTALL_URL" \
  -e SAGE_INSTALL_TAG="${SAGE_INSTALL_TAG:-${SAGEBOT_INSTALL_TAG:-latest}}" \
  -e SAGE_E2E_MODELS="$SAGE_E2E_MODELS" \
  -e SAGE_INSTALL_E2E_PREVIOUS="${SAGE_INSTALL_E2E_PREVIOUS:-${SAGEBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e SAGE_INSTALL_E2E_SKIP_PREVIOUS="${SAGE_INSTALL_E2E_SKIP_PREVIOUS:-${SAGEBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
